# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SPRD) += sc9836-openphone.dtb 	\
			sp9860g-1h10.dtb		\
			sp9863a-1h10.dtb		\
			sp9832e-1h10.dtb		\
			ums512-1h10.dtb			\
			ums512-infinix-x6816d.dtb    \
			ums9230-reeder-s19mps.dtb	\
			ums9620-2h10.dtb
