# SPDX-License-Identifier: GPL-2.0
# Spreadtrum Audio Support

snd-soc-sprd-common-y := sprd-card-common.o
snd-soc-sprd-platform-y := sprd-pcm-dma.o sprd-pcm-compress.o
snd-soc-vbc-v4-dsp-y := vbc-v4-dsp.o
snd-soc-ums9230-y := ums9230-card.o

obj-$(CONFIG_SND_SOC_SPRD_COMMON) += snd-soc-sprd-common.o
obj-$(CONFIG_SND_SOC_SPRD_MCDT) += sprd-mcdt.o
obj-$(CONFIG_SND_SOC_SPRD_PLATFORM) += snd-soc-sprd-platform.o
obj-$(CONFIG_SND_SOC_SPRD_UMS9230) += snd-soc-ums9230.o
obj-$(CONFIG_SND_SOC_SPRD_VBC_V4_DSP) += snd-soc-vbc-v4-dsp.o
