# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PINCTRL_SPRD)		+= pinctrl-sprd.o
obj-$(CONFIG_PINCTRL_SPRD_SC9832E)	+= pinctrl-sprd-sc9832e.o
obj-$(CONFIG_PINCTRL_SPRD_SC9860)	+= pinctrl-sprd-sc9860.o
obj-$(CONFIG_PINCTRL_SPRD_UMS512)	+= pinctrl-sprd-ums512.o
obj-$(CONFIG_PINCTRL_SPRD_UMS9230)	+= pinctrl-sprd-ums9230.o
